import dynamic from "next/dynamic";

import "./globals.css";
import { Inter } from "next/font/google";

// const Header = dynamic(() => import("@/components/Header"));
// const Headerscroll = dynamic(() => import("@/components/Headerscroll"));

// const { Header, Headertwo } = DynamicHeader;
// import { Header, Headertwo } from "@/components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const show = false;

  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
